Repository strangebuzz/MicroSymfony, pull requests merged in 2024-09, with the labels that each got.

#56 chore: Twig update for security issue
  composer.lock
  vendor-bin/php-cs-fixer/composer.lock
Labels: chore, security

#58 Test use ADR controller class FQCN as route name
  README.md
  castor.php
  config/routes.yaml
  src/Controller/ComposerAction.php
  src/Controller/FormAction.php
  src/Controller/HelloWorldAction.php
  src/Controller/HomeAction.php
  src/Controller/SlugifyAction.php
  src/Twig/Extension/RoutingExtension.php
  templates/App/Controller/ComposerAction.html.twig
  templates/App/Controller/FormAction.html.twig
  templates/App/Controller/HelloWorldAction.html.twig
  templates/App/Controller/HomeAction.html.twig
  templates/App/Controller/StimulusAction.html.twig
  templates/base.html.twig
  tests/Integration/Twig/Extension/RoutingExtensionTest.php
Labels: enhancement, UX (User eXperience)

#59 Add auto-generated smoke tests
  tests/Functional/Controller/StaticRoutesSmokeTest.php
Labels: enhancement

#61 feat: add the maker bundle
  composer.json
  composer.lock
  config/bundles.php
  symfony.lock
Labels: UX (User eXperience), feature, dependencies

#62 chore: Symfony 7.1.5 upgrade
  composer.lock
  vendor-bin/php-cs-fixer/composer.lock
Labels: chore, dependencies

#63 chore: add LICENSE
  LICENSE
Labels: chore

#64 docs: new feature branches section
  README.md
Labels: documentation
