Repository strangebuzz/MicroSymfony, pull requests merged in 2024-10, with the labels that each got.

#67 docs: add COC
  CODE_OF_CONDUCT.md
Labels: documentation, UX (User eXperience)

#68 docs: contributors
  CONTRIBUTORS.md
Labels: documentation

#69 feat: enable PHPStan bleeding edge mode
  Makefile
  README.md
  bin/coverage-checker.php
  castor.php
  phpstan.neon
  src/Form/Type/RegisterForm.php
Labels: enhancement, UX (User eXperience)

#70 docs: added a scc report
  scc
Labels: documentation

#73 feat: better coverage threshold handling
  Makefile
  README.md
  castor.php
Labels: DX, improvement

#74 docs: better feature branches section
  README.md
Labels: documentation

#77 docs: initialized badges
  README.md
Labels: documentation, improvement

#78 ci: add scrutinizer-ci
  README.md
  scrutinizer-ci.yaml
Labels: documentation, security

#79 docs: add scrutinizer coverage report link
  README.md
Labels: documentation

#80 feat: add security policy
  .github/workflows/symfony.yml
  CODE_OF_CONDUCT.md
  SECURITY.md
Labels: documentation, chore, security

#82 docs: add a bug report template
  .github/ISSUE_TEMPLATE/1_Bug_report.yaml
Labels: documentation

#83 docs: add GitHub templates
  .github/ISSUE_TEMPLATE/2_Feature_request.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, GitHub

#84 docs: add a contribution quide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  LICENSE
  README.md
  tests/Functional/Controller/StaticRoutesSmokeTest.php
Labels: documentation, DX

#87 fix: fixed env case in Makefile
  Makefile
Labels: chore

#88 docs: added references to the taskfile feature branch
  README.md
Labels: documentation

#89 docs: fix typo
  README.md
Labels: documentation

#92 docs: added table of content
  README.md
Labels: documentation, DX

#102 docs: added the PHP version badge
  README.md
Labels: documentation

#106 chore: Symfony 7.1.6 update
  composer.lock
  vendor-bin/php-cs-fixer/composer.lock
Labels: chore, dependencies
