Repository strangebuzz/MicroSymfony, pull requests merged in 2025-02, with the labels that each got.

#162 chore: cleanup for Psalm level 1
  tests/Functional/Controller/StaticRoutesSmokeTest.php
  tests/bootstrap.php
Labels: chore, DX, improvement

#164 docs: added Psalm and Vite-Bundle feature branches references
  README.md
Labels: documentation

#167 chore: removed scc report
  scc
Labels: chore

#170 docs: notes related to Laragon
  README.md
Labels: documentation

#171 docs: notes related to Laragon (tuning)
  README.md
  docs/laragon.md
Labels: documentation, improvement

#165 feat: add container auto tests
  config/services.php
  tests/Integration/ContainerTest.php
Labels: DX, feature, improvement

#174 fix: better if assertion in tests (psalm level1)
  tests/Integration/ContainerTest.php
Labels: chore, improvement

#175 feat: add the missing symfony/debug-bundle
  README.md
  composer.json
  composer.lock
  config/bundles.php
  config/packages/debug.php
  symfony.lock
Labels: DX, feature, improvement

#177 chore: Symfony 7.2.4 update
  composer.lock
  vendor-bin/php-cs-fixer/composer.lock
Labels: chore, dependencies

#178 docs: cleanup before release
  README.md
  docs/laragon.md
Labels: documentation
